baseURL = "https://hanamichi.wiki"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "Hanamichi的博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-156166070-1"

disqusShortname = "x893675"

enableRobotsTXT = true

hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#84a4b0"
  #background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Hanamichi"
  description = "Hanamichi的学习生活记录"
  avatar = "/me/hanamichi.jpg"
  motto = "勤练带来力量！"
  
  email = "x893675@gmail.com"
  github = "x893675"
  #linkedin = ""
  #codepen = ""
  #stackoverflow = ""

  siteStartYear = 2017

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
